---
name: Scalar-Induce
version: 0.02
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Unfolding scalars
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Scalar-Induce
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build: 0.25
  Test::Differences: 0
  Test::More: 0
recommends:
  ExtUtils::CBuilder: 0.15
provides:
  Scalar::Induce:
    file: lib/Scalar/Induce.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - induce
  - reduce
