---
abstract: 'Unfolding scalars'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  B: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.4005
  Test::Differences: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4005
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scalar-Induce
requires:
  Carp: 0
  Exporter: 5.57
  XSLoader: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Scalar-Induce
  repository: git://github.com/Leont/scalar-induce.git
version: 0.05
